### ISSUE TITLE
Úkol 1

### ISSUE THREAD

**Issue by pet-pecharova** [pet-pecharova/python_092023#1]
Děkuji, @MonikaDvorackova :)

**Comment by MonikaDvorackova** [comment]
Ahoj Peti, 

úkol je hezky zpracovaný, pro lepší přehled o datech by bylo průběžně možné ukázat je nějak graficky, ale v zadání to nebylo. Výsledky jsou správně, děkuju za přehledný zápis výsledků! Splněno v pořádku. Díky a hezký zbytek dne. :)

**Comment by pet-pecharova** [comment]
Ahoj,

moc děkuji. Vlastně jsem původně při řešení úloh nějaké grafy používala, ale do finální verze jsem je nakonec nedala právě proto, že to nebylo v zadání 🙃  Tak příště :)

Díky a přeji hezký večer
